feat(cli): adds status cmd to fetch block height
piplabs/story pull request #108
Opened 2024-09-11 15:17 UTC by leeren

adds validator CLI subcommand for returning block height

issue: fixes #107

2024-09-11 18:37 UTC, limengformal approved these changes

2024-09-11 18:47 UTC, leeren commented on client/cmd/validator.go
> +	client := &http.Client{}
Added

2024-09-11 18:52 UTC, edisonz0718 requested changes
Need to confirm if this is how cosmovisor use it

2024-09-12 04:44 UTC, leeren commented on client/cmd/validator.go
> +	type statusResponse struct {
Updated to use the RPC client!

2024-09-12 07:14 UTC, leeren commented
> Need to confirm if this is how cosmovisor use it

Confirmed to work on cosmovisor after simulating a local upgrade

2024-09-12 07:36 UTC, limengformal approved these changes

2024-09-12 08:17 UTC, merged